#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 osfanbuff63
#
# SPDX-License-Identifier: Apache-2.0

# requires git and poetry
kill -9 "$1"
echo Updating...
git pull
poetry install
echo Running bot!
poetry run nohup pkw-tracking-bot &
